# Generated by Django 3.1.4 on 2020-12-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pub_date',
        ),
    ]
